-- Se você já rodou a versão anterior deste script (com a coluna responsavel_matricula),
-- rode esta linha antes de continuar para remover a coluna que não existe mais no formulário:
-- alter table public.matriculas drop column if exists responsavel_matricula;

-- Tabela de matrículas enviadas pelo formulário público /matricula
create table if not exists public.matriculas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  curso text not null,
  nome_completo text not null,
  cpf text not null,
  data_nascimento date not null,
  rg text not null,
  orgao_emissor text not null,
  data_emissao date,
  naturalidade text not null,
  raca_cor text,
  estado_civil text not null,
  pai text,
  mae text,
  cep text not null,
  rua text not null,
  numero text not null,
  complemento text,
  bairro text not null,
  cidade text not null,
  estado text not null,
  telefone text not null,
  email text not null,
  anexos text[] default '{}',
  observacoes text
);

alter table public.matriculas enable row level security;

-- Qualquer visitante (o formulário público, sem login) pode enviar uma matrícula
create policy "Qualquer um pode inserir matricula"
  on public.matriculas for insert
  to anon, authenticated
  with check (true);

-- Só o admin logado (authenticated) pode ver e apagar matrículas
create policy "Admin pode ver matriculas"
  on public.matriculas for select
  to authenticated
  using (true);

create policy "Admin pode apagar matriculas"
  on public.matriculas for delete
  to authenticated
  using (true);

-- Bucket PRIVADO para os anexos (RG, CPF, comprovantes...) — não é público como o 'banners'
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'matriculas-anexos',
  'matriculas-anexos',
  false,
  10485760, -- 10MB por arquivo
  array['image/png', 'image/jpeg', 'image/webp', 'application/pdf']
)
on conflict (id) do nothing;

-- Qualquer visitante pode enviar um anexo (upload) para esse bucket
create policy "Qualquer um pode enviar anexo de matricula"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'matriculas-anexos');

-- Só o admin logado pode ver/baixar os anexos (usado para gerar o link temporário no painel)
create policy "Admin pode ver anexos de matricula"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'matriculas-anexos');

create policy "Admin pode apagar anexos de matricula"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'matriculas-anexos');
