-- Sistema de múltiplos modelos de pop-up: adiciona suporte a modelos (banner, cupom,
-- captura com imagem, cadastro com desconto) sobre a tabela `popups` já existente, sem
-- perder os pop-ups já cadastrados no formato antigo (só imagem + link). Rode este script
-- uma vez no SQL Editor do Supabase.

create table if not exists public.popups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  titulo text,
  imagem_url text,
  link_redirecionamento text,
  ativo boolean not null default false
);

alter table public.popups enable row level security;

-- Novas colunas: `modelo` identifica o template (bate com a chave usada no registry do
-- front-end, em src/components/popups/registry.js) e `dados` guarda os campos específicos
-- de cada modelo (título, descrição, imagem, texto/link do botão, etc.) em JSON.
alter table public.popups add column if not exists modelo text not null default 'banner';
alter table public.popups add column if not exists dados jsonb not null default '{}'::jsonb;

-- Pop-ups criados antes dos modelos existirem: copia os campos antigos para dentro de
-- `dados` no formato esperado pelo modelo "banner", pra continuarem funcionando sem
-- precisar recriar nada.
update public.popups
set dados = jsonb_build_object(
  'imagem_url', imagem_url,
  'link_redirecionamento', coalesce(link_redirecionamento, '')
)
where dados = '{}'::jsonb and imagem_url is not null;

-- Políticas da tabela popups (idempotente: remove e recria caso já existam de antes)
drop policy if exists "Qualquer um pode ver popups ativos" on public.popups;
create policy "Qualquer um pode ver popups ativos"
  on public.popups for select
  to anon, authenticated
  using (ativo = true);

drop policy if exists "Admin pode ver todos os popups" on public.popups;
create policy "Admin pode ver todos os popups"
  on public.popups for select
  to authenticated
  using (true);

drop policy if exists "Admin pode inserir popups" on public.popups;
create policy "Admin pode inserir popups"
  on public.popups for insert
  to authenticated
  with check (true);

drop policy if exists "Admin pode atualizar popups" on public.popups;
create policy "Admin pode atualizar popups"
  on public.popups for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Admin pode apagar popups" on public.popups;
create policy "Admin pode apagar popups"
  on public.popups for delete
  to authenticated
  using (true);

-- Tabela de e-mails capturados pelo modelo "captura" (imagem + formulário de e-mail)
create table if not exists public.popup_capturas_email (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  popup_id bigint references public.popups(id) on delete set null,
  email text not null
);

alter table public.popup_capturas_email enable row level security;

drop policy if exists "Qualquer um pode enviar seu email" on public.popup_capturas_email;
create policy "Qualquer um pode enviar seu email"
  on public.popup_capturas_email for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admin pode ver capturas de email" on public.popup_capturas_email;
create policy "Admin pode ver capturas de email"
  on public.popup_capturas_email for select
  to authenticated
  using (true);

drop policy if exists "Admin pode apagar capturas de email" on public.popup_capturas_email;
create policy "Admin pode apagar capturas de email"
  on public.popup_capturas_email for delete
  to authenticated
  using (true);

-- Tabela de cadastros (nome + e-mail) do modelo "cadastro" (imagem + selo de desconto)
create table if not exists public.popup_cadastros (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  popup_id bigint references public.popups(id) on delete set null,
  nome text not null,
  email text not null
);

alter table public.popup_cadastros enable row level security;

drop policy if exists "Qualquer um pode se cadastrar" on public.popup_cadastros;
create policy "Qualquer um pode se cadastrar"
  on public.popup_cadastros for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admin pode ver cadastros" on public.popup_cadastros;
create policy "Admin pode ver cadastros"
  on public.popup_cadastros for select
  to authenticated
  using (true);

drop policy if exists "Admin pode apagar cadastros" on public.popup_cadastros;
create policy "Admin pode apagar cadastros"
  on public.popup_cadastros for delete
  to authenticated
  using (true);
