-- ============================================================================
-- Menu "Sorteios" da Navbar
-- ----------------------------------------------------------------------------
-- Cria a tabela que alimenta o dropdown de Sorteios no menu do site.
-- Cada linha é um sorteio/campanha; só aparecem no menu os que estão ativos e
-- dentro do período (data_inicio / data_fim). Gerenciável em /admin > Sorteios.
-- Rode este arquivo uma única vez no SQL Editor do Supabase.
-- ============================================================================

create table if not exists public.sorteios (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  link text not null default '/sorteios',
  ativo boolean not null default true,
  data_inicio date,
  data_fim date,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.sorteios is
  'Sorteios exibidos no dropdown "Sorteios" da Navbar. Só entram no menu os ativos e dentro do período.';
comment on column public.sorteios.descricao is
  'Linha de apoio mostrada abaixo do nome no menu (ex.: "Gire e ganhe cashback").';
comment on column public.sorteios.link is
  'Destino do item: rota interna (ex.: /sorteios) ou URL completa (https://...).';
comment on column public.sorteios.data_inicio is
  'Data em que o sorteio começa a aparecer no menu. Nulo = já está no ar.';
comment on column public.sorteios.data_fim is
  'Último dia em que o sorteio aparece no menu. Nulo = sem data para encerrar.';
comment on column public.sorteios.ordem is
  'Posição no menu. Menor número aparece primeiro.';

-- Ordenação do menu
create index if not exists sorteios_ordem_idx on public.sorteios (ordem, created_at);

-- --- Permissões -------------------------------------------------------------
alter table public.sorteios enable row level security;

-- Qualquer visitante do site pode ler (o menu é público)
drop policy if exists "Sorteios visíveis para todos" on public.sorteios;
create policy "Sorteios visíveis para todos"
  on public.sorteios for select
  using (true);

-- Só quem está logado no painel pode criar/editar/excluir
drop policy if exists "Sorteios gerenciados por autenticados" on public.sorteios;
create policy "Sorteios gerenciados por autenticados"
  on public.sorteios for all
  to authenticated
  using (true)
  with check (true);

-- --- Sorteio que já existe hoje --------------------------------------------
insert into public.sorteios (nome, descricao, link, ativo, ordem)
select 'Roleta Premiada', 'Gire e concorra a cashback e descontos', '/sorteios', true, 0
where not exists (select 1 from public.sorteios where link = '/sorteios');
