create table if not exists public.redes_sociais (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  link text not null,
  imagem_url text
);

alter table public.redes_sociais enable row level security;

drop policy if exists "Qualquer um pode ver redes_sociais" on public.redes_sociais;
create policy "Qualquer um pode ver redes_sociais"
  on public.redes_sociais for select
  to anon, authenticated using (true);

drop policy if exists "Admin pode inserir redes_sociais" on public.redes_sociais;
create policy "Admin pode inserir redes_sociais"
  on public.redes_sociais for insert
  to authenticated with check (true);

drop policy if exists "Admin pode atualizar redes_sociais" on public.redes_sociais;
create policy "Admin pode atualizar redes_sociais"
  on public.redes_sociais for update
  to authenticated using (true) with check (true);

drop policy if exists "Admin pode apagar redes_sociais" on public.redes_sociais;
create policy "Admin pode apagar redes_sociais"
  on public.redes_sociais for delete
  to authenticated using (true);

-- Valor inicial: os 5 cards que já estavam fixos no código, pra não mudar nada
-- visualmente até o admin editar pelo painel. imagem_url fica null aqui porque as fotos
-- originais são arquivos locais (src/assets) — o admin precisa reenviar cada foto pelo
-- painel para que os cards passem a exibi-las.
insert into public.redes_sociais (nome, link)
select * from (values
  ('Facebook', 'https://www.facebook.com/estudeseguro.oficial/'),
  ('Instagram', 'https://www.instagram.com/estudeseguroead/'),
  ('YouTube', 'https://www.youtube.com/@EstudeSeguro'),
  ('Reclame Aqui', 'https://www.reclameaqui.com.br/empresa/estude-seguro-ltda/'),
  ('Google Meu Negócio', 'https://share.google/hnhzdmj3M9gNmODgZ')
) as seed(nome, link)
where not exists (select 1 from public.redes_sociais);
