-- ============================================================================
-- SEGURANÇA 08 — CORREÇÃO: o rate limit não estava funcionando
-- ----------------------------------------------------------------------------
-- O PROBLEMA (medido em produção, não suposto)
--
-- `enviar_matricula` tem limite de 5 chamadas por hora por IP. Sete chamadas
-- seguidas do mesmo IP passaram todas. O mesmo com `girar_roleta_resgate`
-- (limite 10): doze chamadas, nenhuma barrada.
--
-- Como `enviar_matricula` é uma função nova, criada pelo arquivo 03, e ela
-- obrigatoriamente chama `consumir_rate_limit` na primeira linha, a conclusão
-- é que `consumir_rate_limit` está devolvendo `true` sempre.
--
-- SENDO HONESTO SOBRE O DIAGNÓSTICO
--
-- Não consigo consultar seu banco, então não sei qual dos candidatos abaixo é
-- o culpado. Este arquivo faz duas coisas: a PARTE 1 mostra o que está
-- acontecendo (e a saída me diz a causa exata), e a PARTE 2 reescreve a função
-- de um jeito que elimina os três candidatos de uma vez.
--
-- Candidatos:
--
--   (a) `force row level security` na tabela de contadores, somado a zero
--       policies. FORCE faz a RLS valer até para o dono da tabela. Se o papel
--       que executa a função não tiver BYPASSRLS, o `returning` do upsert pode
--       não devolver linha nenhuma — e aí a contagem vira NULL. Como
--       `NULL <= 5` é NULL, e `if not NULL` não entra no ramo, o limite nunca
--       dispara. Falha silenciosa, exatamente o sintoma observado.
--
--   (b) A referência `public.seguranca_rate_limit.contagem` dentro do
--       `on conflict do update`. Ali o certo é usar só o nome da tabela; a
--       forma qualificada com o schema pode não resolver.
--
--   (c) `identidade_requisicao()` devolvendo um valor diferente a cada
--       chamada, o que faria cada requisição criar uma linha nova em vez de
--       incrementar a existente.
--
-- A PARTE 2 troca o upsert por "uma linha por evento + contagem em janela
-- deslizante", que é mais simples, não depende de `on conflict`, não depende do
-- `returning`, e ainda melhora o comportamento: a janela passa a ser deslizante
-- de verdade, em vez de zerar de hora cheia em hora cheia.
--
-- PRÉ-REQUISITO: arquivos 01 a 04 já rodados.
-- ============================================================================

-- ###########################################################################
-- PARTE 1 — DIAGNÓSTICO (rode e me mande a saída)
-- ###########################################################################

-- 1.1 O que foi parar na tabela de contadores?
-- Se vier vazia: a função nem está gravando (candidato a ou b).
-- Se vier com várias linhas de contagem = 1: está gravando mas não
-- incrementando (candidato b ou c) — repare se a coluna identidade varia.
select chave, identidade, janela, contagem
from public.seguranca_rate_limit
order by janela desc, chave
limit 30;

-- 1.2 Dono da tabela, RLS e FORCE
select
  c.relname                     as tabela,
  pg_get_userbyid(c.relowner)   as dono,
  c.relrowsecurity              as rls,
  c.relforcerowsecurity         as rls_forcada,
  (select count(*) from pg_policies p
    where p.schemaname = 'public' and p.tablename = c.relname) as policies
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relname = 'seguranca_rate_limit';

-- 1.3 O dono das funções tem BYPASSRLS? (decide se o candidato (a) procede)
select rolname, rolsuper, rolbypassrls
from pg_roles
where rolname in ('postgres', 'authenticator', 'supabase_admin');

-- 1.4 O que identidade_requisicao() enxerga nesta chamada
select public.identidade_requisicao() as identidade_vista;

-- ###########################################################################
-- PARTE 2 — CORREÇÃO
-- ###########################################################################

-- 2.1 Tabela nova: uma linha por evento, sem upsert.
drop table if exists public.seguranca_rate_limit;

create table public.seguranca_rate_limit (
  id          bigint generated by default as identity primary key,
  chave       text        not null,
  identidade  text        not null,
  ocorrido_em timestamptz not null default now()
);

comment on table public.seguranca_rate_limit is
  'Um registro por tentativa, para contagem em janela deslizante. Escrita só por '
  'funções SECURITY DEFINER; nenhum papel público tem acesso.';

create index seguranca_rate_limit_busca_idx
  on public.seguranca_rate_limit (chave, identidade, ocorrido_em desc);

revoke all on public.seguranca_rate_limit from anon, authenticated;
alter table public.seguranca_rate_limit enable row level security;

-- Sem `force`: a RLS continua barrando anon e authenticated (que nem GRANT
-- têm), mas para de atrapalhar a própria função que precisa gravar ali.
-- Esta é a diferença que resolve o candidato (a).
alter table public.seguranca_rate_limit no force row level security;

-- 2.2 Função reescrita
create or replace function public.consumir_rate_limit(
  p_chave  text,
  p_limite integer,
  p_janela interval
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_identidade text;
  v_contagem   integer;
begin
  v_identidade := public.identidade_requisicao();

  -- Faxina: descarta o que já não conta para janela nenhuma.
  delete from public.seguranca_rate_limit
  where ocorrido_em < now() - interval '1 day';

  -- Registra a tentativa atual.
  insert into public.seguranca_rate_limit (chave, identidade)
  values (p_chave, v_identidade);

  -- Conta as tentativas dentro da janela deslizante, incluindo esta.
  select count(*) into v_contagem
  from public.seguranca_rate_limit r
  where r.chave = p_chave
    and r.identidade = v_identidade
    and r.ocorrido_em > now() - p_janela;

  -- coalesce blinda contra o modo de falha silenciosa: se a contagem viesse
  -- NULL por qualquer motivo, o antigo `NULL <= limite` dava NULL e o `if not`
  -- não entrava no ramo, liberando tudo. Agora, na dúvida, bloqueia.
  return coalesce(v_contagem, p_limite + 1) <= p_limite;
end;
$$;

alter function public.consumir_rate_limit(text, integer, interval) owner to postgres;
revoke all on function public.consumir_rate_limit(text, integer, interval) from public, anon, authenticated;

-- 2.3 Teste automático de verdade: chama a função 7 vezes com limite 5
-- e confere que as duas últimas são recusadas.
do $$
declare
  v_ok       boolean;
  v_liberou  integer := 0;
  v_bloqueou integer := 0;
  i          integer;
begin
  delete from public.seguranca_rate_limit where chave = 'autoteste';

  for i in 1..7 loop
    v_ok := public.consumir_rate_limit('autoteste', 5, interval '1 hour');
    if v_ok then v_liberou := v_liberou + 1; else v_bloqueou := v_bloqueou + 1; end if;
  end loop;

  delete from public.seguranca_rate_limit where chave = 'autoteste';

  if v_liberou = 5 and v_bloqueou = 2 then
    raise notice 'OK: rate limit funcionando (5 liberadas, 2 bloqueadas em 7 tentativas).';
  else
    raise warning 'FALHA: esperado 5 liberadas e 2 bloqueadas, obtive % e %.',
      v_liberou, v_bloqueou;
  end if;
end;
$$;
