-- Tabela de frases exibidas na esteira animada da Home (substitui os selos nessa esteira)
create table if not exists public.frases (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  texto text not null
);

alter table public.frases enable row level security;

-- Qualquer visitante do site (sem login) pode ver as frases na Home
create policy "Qualquer um pode ver frases"
  on public.frases for select
  to anon, authenticated
  using (true);

-- Só o admin logado pode adicionar frases
create policy "Admin pode inserir frases"
  on public.frases for insert
  to authenticated
  with check (true);

-- Só o admin logado pode apagar frases
create policy "Admin pode apagar frases"
  on public.frases for delete
  to authenticated
  using (true);
