
create table if not exists public.resgate_funcionarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.resgate_funcionarios is
  'Funcionários participantes da campanha "Resgate seu Prêmio". Aparecem na lista de "quem indicou" e no ranking.';

-- Prêmios da roleta, com o peso definindo a chance de cada um sair
create table if not exists public.resgate_premios (
  id bigint generated by default as identity primary key,
  nome text not null,
  rotulo text,
  rotulo_secundario text,
  peso integer not null default 1 check (peso >= 0),
  ativo boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.resgate_premios is
  'Prêmios da roleta "Resgate seu Prêmio".';
comment on column public.resgate_premios.nome is
  'Nome do prêmio usado no resultado, no histórico e no relatório do admin.';
comment on column public.resgate_premios.rotulo is
  'Linha 1 escrita dentro da fatia da roleta (ex.: "10%"). Vazio = usa o nome.';
comment on column public.resgate_premios.rotulo_secundario is
  'Linha 2 escrita dentro da fatia da roleta (ex.: "DE DESCONTO"). Opcional.';
comment on column public.resgate_premios.peso is
  'Chance relativa de sair. Peso 3 sai 3x mais que peso 1. Peso 0 nunca sai.';

-- Vouchers: um por indicação. Cada linha vira também o registro do giro.
create table if not exists public.resgate_vouchers (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  usado boolean not null default false,
  created_at timestamptz not null default now(),
  usado_em timestamptz,
  participante_nome text,
  funcionario_id bigint references public.resgate_funcionarios (id) on delete set null,
  funcionario_nome text,
  premio_id bigint references public.resgate_premios (id) on delete set null,
  premio_nome text
);

comment on table public.resgate_vouchers is
  'Vouchers da campanha "Resgate seu Prêmio". Uso único: ao girar, a linha guarda quem girou, quem indicou e o prêmio sorteado.';
comment on column public.resgate_vouchers.codigo is
  'Código de 5 caracteres (A-Z e 2-9) entregue à pessoa indicada. Sempre em maiúsculas.';
comment on column public.resgate_vouchers.funcionario_nome is
  'Nome do funcionário copiado no momento do giro, para o histórico não se perder se o cadastro dele for apagado.';

create index if not exists resgate_vouchers_usado_idx on public.resgate_vouchers (usado, created_at desc);
create index if not exists resgate_vouchers_funcionario_idx on public.resgate_vouchers (funcionario_id) where usado;

-- Banners do hero (carrossel no topo da página /resgate-premio)
create table if not exists public.resgate_banners (
  id bigint generated by default as identity primary key,
  imagem_url text not null,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.resgate_banners is
  'Banners do carrossel no topo da página "Resgate seu Prêmio". O de menor ordem é a capa.';

-- ============================ PERMISSÕES ====================================

alter table public.resgate_banners enable row level security;

drop policy if exists "Banners do resgate visíveis para todos" on public.resgate_banners;
create policy "Banners do resgate visíveis para todos"
  on public.resgate_banners for select
  using (true);

drop policy if exists "Banners do resgate gerenciados por autenticados" on public.resgate_banners;
create policy "Banners do resgate gerenciados por autenticados"
  on public.resgate_banners for all
  to authenticated
  using (true)
  with check (true);

alter table public.resgate_funcionarios enable row level security;
alter table public.resgate_premios enable row level security;
alter table public.resgate_vouchers enable row level security;

-- A página pública precisa listar os funcionários (select "quem indicou")
drop policy if exists "Funcionários visíveis para todos" on public.resgate_funcionarios;
create policy "Funcionários visíveis para todos"
  on public.resgate_funcionarios for select
  using (true);

drop policy if exists "Funcionários gerenciados por autenticados" on public.resgate_funcionarios;
create policy "Funcionários gerenciados por autenticados"
  on public.resgate_funcionarios for all
  to authenticated
  using (true)
  with check (true);

-- A página pública precisa dos prêmios para desenhar as fatias da roleta
drop policy if exists "Prêmios do resgate visíveis para todos" on public.resgate_premios;
create policy "Prêmios do resgate visíveis para todos"
  on public.resgate_premios for select
  using (true);

drop policy if exists "Prêmios do resgate gerenciados por autenticados" on public.resgate_premios;
create policy "Prêmios do resgate gerenciados por autenticados"
  on public.resgate_premios for all
  to authenticated
  using (true)
  with check (true);

-- Vouchers NUNCA são legíveis pelo público: senão qualquer visitante baixaria
-- a lista de códigos válidos. Só o painel (logado) enxerga, e o giro acontece
-- pela função abaixo, que roda com permissão elevada.
drop policy if exists "Vouchers só para autenticados" on public.resgate_vouchers;
create policy "Vouchers só para autenticados"
  on public.resgate_vouchers for all
  to authenticated
  using (true)
  with check (true);

-- ============================ FUNÇÕES =======================================

-- Gera N vouchers de uma vez e devolve os códigos criados.
-- Alfabeto sem 0/O/1/I/L para ninguém errar ao digitar o código.
create or replace function public.gerar_vouchers_resgate(p_quantidade integer)
returns table (id bigint, codigo text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_alfabeto constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_codigo text;
  v_tentativas integer;
  i integer;
  j integer;
begin
  if p_quantidade is null or p_quantidade < 1 or p_quantidade > 200 then
    raise exception 'Quantidade de vouchers deve ficar entre 1 e 200.';
  end if;

  for i in 1..p_quantidade loop
    v_tentativas := 0;
    loop
      v_codigo := '';
      for j in 1..5 loop
        v_codigo := v_codigo || substr(v_alfabeto, floor(random() * length(v_alfabeto))::int + 1, 1);
      end loop;

      exit when not exists (select 1 from resgate_vouchers v where v.codigo = v_codigo);

      v_tentativas := v_tentativas + 1;
      if v_tentativas > 50 then
        raise exception 'Não foi possível gerar um código novo. Tente novamente.';
      end if;
    end loop;

    return query
      insert into resgate_vouchers (codigo)
      values (v_codigo)
      returning resgate_vouchers.id, resgate_vouchers.codigo;
  end loop;
end;
$$;

revoke all on function public.gerar_vouchers_resgate(integer) from public, anon;
grant execute on function public.gerar_vouchers_resgate(integer) to authenticated;

-- Gira a roleta do resgate. Valida o voucher, sorteia o prêmio por peso e
-- queima o voucher na mesma transação.
--
-- resultado: 'sucesso' | 'voucher_invalido' | 'voucher_ja_usado'
--            | 'funcionario_invalido' | 'sem_premios'
create or replace function public.girar_roleta_resgate(
  p_nome_completo text,
  p_codigo text,
  p_funcionario_id bigint
)
returns table (
  resultado text,
  premio_id bigint,
  premio_nome text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo text;
  v_voucher resgate_vouchers%rowtype;
  v_funcionario resgate_funcionarios%rowtype;
  v_total integer;
  v_sorteio integer;
  v_premio resgate_premios%rowtype;
  v_atualizados integer;
begin
  if p_nome_completo is null or length(trim(p_nome_completo)) < 3 then
    return query select 'voucher_invalido'::text, null::bigint, null::text;
    return;
  end if;

  v_codigo := upper(trim(coalesce(p_codigo, '')));

  select * into v_funcionario
  from resgate_funcionarios
  where id = p_funcionario_id and ativo;

  if not found then
    return query select 'funcionario_invalido'::text, null::bigint, null::text;
    return;
  end if;

  -- Trava a linha do voucher até o fim da transação: dois giros simultâneos
  -- com o mesmo código não conseguem passar os dois.
  select * into v_voucher
  from resgate_vouchers
  where codigo = v_codigo
  for update;

  if not found then
    return query select 'voucher_invalido'::text, null::bigint, null::text;
    return;
  end if;

  if v_voucher.usado then
    return query select 'voucher_ja_usado'::text, null::bigint, null::text;
    return;
  end if;

  select coalesce(sum(peso), 0) into v_total
  from resgate_premios
  where ativo and peso > 0;

  if v_total = 0 then
    return query select 'sem_premios'::text, null::bigint, null::text;
    return;
  end if;

  v_sorteio := floor(random() * v_total)::int + 1;

  -- Sorteio por peso: soma acumulada e pega a primeira faixa que alcança o número
  select p.* into v_premio
  from (
    select
      r.*,
      sum(r.peso) over (order by r.ordem, r.id rows between unbounded preceding and current row) as acumulado
    from resgate_premios r
    where r.ativo and r.peso > 0
  ) p
  where p.acumulado >= v_sorteio
  order by p.acumulado
  limit 1;

  if not found then
    return query select 'sem_premios'::text, null::bigint, null::text;
    return;
  end if;

  update resgate_vouchers
  set
    usado = true,
    usado_em = now(),
    participante_nome = trim(p_nome_completo),
    funcionario_id = v_funcionario.id,
    funcionario_nome = v_funcionario.nome,
    premio_id = v_premio.id,
    premio_nome = v_premio.nome
  where id = v_voucher.id and usado = false;

  get diagnostics v_atualizados = row_count;
  if v_atualizados = 0 then
    return query select 'voucher_ja_usado'::text, null::bigint, null::text;
    return;
  end if;

  return query select 'sucesso'::text, v_premio.id, v_premio.nome;
end;
$$;

revoke all on function public.girar_roleta_resgate(text, text, bigint) from public;
grant execute on function public.girar_roleta_resgate(text, text, bigint) to anon, authenticated;

-- ============================ DADOS INICIAIS ================================

-- Prêmios de exemplo — troque tudo pelo painel em /admin > Resgate seu Prêmio
insert into public.resgate_premios (nome, rotulo, rotulo_secundario, peso, ordem)
select * from (values
  ('5% de desconto',  '5%',    'DE DESCONTO', 40, 0),
  ('10% de desconto', '10%',   'DE DESCONTO', 30, 1),
  ('15% de desconto', '15%',   'DE DESCONTO', 15, 2),
  ('25% de desconto', '25%',   'DE DESCONTO', 10, 3),
  ('Curso grátis',    'CURSO', 'GRÁTIS',       5, 4)
) as novos(nome, rotulo, rotulo_secundario, peso, ordem)
where not exists (select 1 from public.resgate_premios);

-- Coloca a campanha no dropdown "Sorteios" da Navbar.
-- Só roda se a tabela `sorteios` já existir (supabase-sorteios-menu-setup.sql).
-- Se ainda não existir, rode aquele arquivo antes e depois este de novo.
do $$
begin
  if to_regclass('public.sorteios') is null then
    raise notice 'Tabela public.sorteios não existe: rode supabase-sorteios-menu-setup.sql para o item aparecer no menu.';
  else
    insert into public.sorteios (nome, descricao, link, ativo, ordem)
    select 'Resgate seu Prêmio', 'Tem um voucher? Gire e descubra seu prêmio', '/resgate-premio', true, 1
    where not exists (select 1 from public.sorteios where link = '/resgate-premio');
  end if;
end;
$$;
