
insert into public.configuracoes (chave, valor) values
  ('sorteio_ativo', 'true'),
  ('sorteio_titulo', ' Gire a Roleta Premiada da Estude Seguro!'),
  ('sorteio_subtitulo', 'Todos os alunos que concluíram sua formação na Estude Seguro podem participar da nossa Roleta Premiada e concorrer a diversos benefícios exclusivos.'),
  ('sorteio_whatsapp_numero', '5511995987197'),
  ('sorteio_whatsapp_mensagem', 'Olá! Acabei de ganhar um prêmio na Roleta da Estude Seguro.

Nome: {{nome}}
CPF: {{cpf}}
Número do certificado: {{numeroMatricula}}

Prêmio ganho: {{premio}}

Gostaria de resgatar meu prêmio.')
on conflict (chave) do nothing;

-- ============================================================
-- 2) PRÊMIOS
-- ============================================================
create table if not exists public.sorteio_premios (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  tipo text not null default 'cashback' check (tipo in ('cashback', 'desconto', 'curso')),
  percentual_cashback numeric,
  peso integer not null default 1 check (peso >= 0),
  ativo boolean not null default true,
  ordem integer not null default 0
);

alter table public.sorteio_premios enable row level security;

drop policy if exists "Qualquer um pode ver premios ativos" on public.sorteio_premios;
create policy "Qualquer um pode ver premios ativos"
  on public.sorteio_premios for select
  to anon, authenticated using (true);

drop policy if exists "Admin pode gerenciar premios" on public.sorteio_premios;
create policy "Admin pode gerenciar premios"
  on public.sorteio_premios for all
  to authenticated using (true) with check (true);

insert into public.sorteio_premios (nome, tipo, percentual_cashback, peso, ordem) values
  ('Cashback de 10%', 'cashback', 10, 20, 1),
  ('Cashback de 15%', 'cashback', 15, 15, 2),
  ('Cashback de 20%', 'cashback', 20, 15, 3),
  ('Cashback de 25%', 'cashback', 25, 10, 4),
  ('Cashback de 30%', 'cashback', 30, 8, 5),
  ('Cashback de 35%', 'cashback', 35, 5, 6),
  ('50% de desconto em uma nova formação', 'desconto', 50, 5, 7),
  ('1 Pós-Técnico ou Pós-Graduação', 'curso', null, 2, 8)
on conflict do nothing;

-- ============================================================
-- 3) BANNERS DO HERO (carrossel da página /sorteios)
-- ============================================================
create table if not exists public.sorteio_banners (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  imagem_url text not null,
  ordem integer not null default 0
);

alter table public.sorteio_banners enable row level security;

drop policy if exists "Qualquer um pode ver banners do sorteio" on public.sorteio_banners;
create policy "Qualquer um pode ver banners do sorteio"
  on public.sorteio_banners for select
  to anon, authenticated using (true);

drop policy if exists "Admin pode gerenciar banners do sorteio" on public.sorteio_banners;
create policy "Admin pode gerenciar banners do sorteio"
  on public.sorteio_banners for all
  to authenticated using (true) with check (true);

-- ============================================================
-- 4) PARTICIPANTES (1 linha por CPF — a constraint unique é a trava real)
-- ============================================================
create table if not exists public.sorteio_participantes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  cpf text not null unique,
  numero_matricula text not null,
  matriculado_id bigint references public.matriculados(id),
  premio text not null,
  premio_tipo text not null,
  percentual_cashback numeric,
  data_sorteio timestamptz not null default now(),
  data_resgate timestamptz,
  resgatado boolean not null default false,
  ip text,
  user_agent text
);

create index if not exists sorteio_participantes_cpf_idx on public.sorteio_participantes (cpf);

alter table public.sorteio_participantes enable row level security;

-- Propositalmente SEM policy de select para anon/authenticated além do admin:
-- contém CPF e nome. Só o painel admin (autenticado) pode listar; o frontend
-- público nunca lê essa tabela diretamente, só recebe o resultado via RPC.
drop policy if exists "Admin pode ver participantes do sorteio" on public.sorteio_participantes;
create policy "Admin pode ver participantes do sorteio"
  on public.sorteio_participantes for select
  to authenticated using (true);

drop policy if exists "Admin pode atualizar participantes do sorteio" on public.sorteio_participantes;
create policy "Admin pode atualizar participantes do sorteio"
  on public.sorteio_participantes for update
  to authenticated using (true) with check (true);

-- Não existe policy de insert para anon/authenticated de propósito: quem grava
-- é exclusivamente a função girar_roleta_premiada (security definer) abaixo.

-- ============================================================
-- 5) FUNÇÃO: girar_roleta_premiada
-- ============================================================
-- Faz tudo atomicamente, no servidor: confere se já participou, confere
-- elegibilidade (matriculados.status_order = 7, "Certificado concluído"),
-- sorteia o prêmio por peso de probabilidade e grava a participação.
-- resultado possíveis: 'ja_participou' | 'sucesso' | 'nao_encontrado' | 'campanha_inativa' | 'sem_premios'
drop function if exists public.girar_roleta_premiada(text, text, text);
create or replace function public.girar_roleta_premiada(
  p_nome_completo text,
  p_cpf text,
  p_numero_matricula text
)
returns table (
  resultado text,
  premio_nome text,
  premio_tipo text,
  percentual_cashback numeric,
  data_sorteio timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cpf_normalizado text := regexp_replace(coalesce(p_cpf, ''), '\D', '', 'g');
  v_matriculado record;
  v_participacao record;
  v_premio record;
  v_total_peso integer;
  v_sorteio numeric;
  v_acumulado integer := 0;
  v_ip text;
  v_user_agent text;
begin
  -- Cabeçalhos reais da requisição HTTP (a chamada via supabase.rpc() passa pelo
  -- PostgREST, que expõe os headers originais aqui). Só para registro/estatística.
  begin
    v_ip := coalesce(
      split_part(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ',', 1),
      null
    );
    v_user_agent := current_setting('request.headers', true)::json ->> 'user-agent';
  exception when others then
    v_ip := null;
    v_user_agent := null;
  end;

  -- 1) já participou com esse CPF?
  select * into v_participacao
  from public.sorteio_participantes
  where cpf = v_cpf_normalizado
  limit 1;

  if found then
    return query select 'ja_participou'::text, v_participacao.premio, v_participacao.premio_tipo,
      v_participacao.percentual_cashback, v_participacao.data_sorteio;
    return;
  end if;

  -- 2) campanha ativa?
  if coalesce((select valor from public.configuracoes where chave = 'sorteio_ativo'), 'true') = 'false' then
    return query select 'campanha_inativa'::text, null::text, null::text, null::numeric, null::timestamptz;
    return;
  end if;

  -- 3) elegível? nome + cpf + número de matrícula/certificado batem e status = certificado concluído
  select * into v_matriculado
  from public.matriculados m
  where lower(trim(m.nome_completo)) = lower(trim(p_nome_completo))
    and regexp_replace(m.cpf, '\D', '', 'g') = v_cpf_normalizado
    and lower(trim(m.numero_matricula)) = lower(trim(coalesce(p_numero_matricula, '')))
    and m.status_order = 7
  limit 1;

  if not found then
    return query select 'nao_encontrado'::text, null::text, null::text, null::numeric, null::timestamptz;
    return;
  end if;

  -- 4) sorteio ponderado entre os prêmios ativos
  select coalesce(sum(peso), 0) into v_total_peso from public.sorteio_premios where ativo = true;
  if v_total_peso <= 0 then
    return query select 'sem_premios'::text, null::text, null::text, null::numeric, null::timestamptz;
    return;
  end if;

  v_sorteio := random() * v_total_peso;

  for v_premio in select * from public.sorteio_premios where ativo = true order by ordem asc, id asc loop
    v_acumulado := v_acumulado + v_premio.peso;
    if v_sorteio <= v_acumulado then
      exit;
    end if;
  end loop;

  -- 5) grava a participação — a constraint unique(cpf) impede corrida (2 giros simultâneos)
  begin
    insert into public.sorteio_participantes
      (nome, cpf, numero_matricula, matriculado_id, premio, premio_tipo, percentual_cashback, ip, user_agent)
    values
      (trim(p_nome_completo), v_cpf_normalizado, trim(p_numero_matricula), v_matriculado.id,
       v_premio.nome, v_premio.tipo, v_premio.percentual_cashback, v_ip, v_user_agent);
  exception when unique_violation then
    select * into v_participacao from public.sorteio_participantes where cpf = v_cpf_normalizado limit 1;
    return query select 'ja_participou'::text, v_participacao.premio, v_participacao.premio_tipo,
      v_participacao.percentual_cashback, v_participacao.data_sorteio;
    return;
  end;

  return query select 'sucesso'::text, v_premio.nome, v_premio.tipo, v_premio.percentual_cashback, now();
end;
$$;

grant execute on function public.girar_roleta_premiada(text, text, text) to anon, authenticated;
