

create table if not exists public.matriculados (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Identificação do acompanhamento
  numero_matricula text not null unique,
  status_order smallint not null default 0 check (status_order between 0 and 7),

  -- Mesmos campos do formulário público /matricula (tabela `matriculas`)
  curso text not null,
  nome_completo text not null,
  cpf text not null,
  data_nascimento date not null,
  rg text not null,
  orgao_emissor text not null,
  data_emissao date,
  naturalidade text not null,
  raca_cor text,
  estado_civil text not null,
  pai text,
  mae text,
  cep text not null,
  rua text not null,
  numero text not null,
  complemento text,
  bairro text not null,
  cidade text not null,
  estado text not null,
  telefone text not null,
  email text not null,
  anexos text[] default '{}',
  observacoes text
);

alter table public.matriculados enable row level security;

drop policy if exists "Admin pode ver matriculados" on public.matriculados;
create policy "Admin pode ver matriculados"
  on public.matriculados for select
  to authenticated using (true);

drop policy if exists "Admin pode inserir matriculados" on public.matriculados;
create policy "Admin pode inserir matriculados"
  on public.matriculados for insert
  to authenticated with check (true);

drop policy if exists "Admin pode atualizar matriculados" on public.matriculados;
create policy "Admin pode atualizar matriculados"
  on public.matriculados for update
  to authenticated using (true) with check (true);

drop policy if exists "Admin pode apagar matriculados" on public.matriculados;
create policy "Admin pode apagar matriculados"
  on public.matriculados for delete
  to authenticated using (true);

-- IMPORTANTE: propositalmente NÃO existe policy de select para `anon`. Se existisse (mesmo
-- filtrando no client com .eq()), qualquer pessoa com a anon key poderia rodar
-- `select * from matriculados` direto e listar todo mundo (incluindo RG, endereço etc). A
-- consulta pública usa a função abaixo, que só devolve uma linha quando as 3 credenciais
-- (nome completo + CPF + data de nascimento) batem exatamente, e só devolve os campos
-- necessários para exibir o progresso — nunca CPF, RG, endereço, telefone, e-mail, anexos
-- ou observações.
drop function if exists public.buscar_status_matricula(text, text, text, date);
create or replace function public.buscar_status_matricula(
  p_nome_completo text,
  p_cpf text,
  p_data_nascimento date
)
returns table (
  numero_matricula text,
  nome_completo text,
  curso text,
  status_order smallint,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select m.numero_matricula, m.nome_completo, m.curso, m.status_order, m.updated_at
  from public.matriculados m
  where lower(trim(m.nome_completo)) = lower(trim(p_nome_completo))
    and regexp_replace(m.cpf, '\D', '', 'g') = regexp_replace(coalesce(p_cpf, ''), '\D', '', 'g')
    and m.data_nascimento = p_data_nascimento
  limit 1;
$$;

grant execute on function public.buscar_status_matricula(text, text, date) to anon, authenticated;

-- Mantém updated_at em dia sempre que o admin alterar status ou dados do aluno.
create or replace function public.tocar_updated_at_matriculados()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_matriculados_updated_at on public.matriculados;
create trigger trg_matriculados_updated_at
  before update on public.matriculados
  for each row
  execute function public.tocar_updated_at_matriculados();
