create table if not exists public.trajetoria (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ano text not null,
  categoria text not null,
  titulo text not null,
  descricao text not null,
  imagem_url text
);

alter table public.trajetoria enable row level security;

drop policy if exists "Qualquer um pode ver trajetoria" on public.trajetoria;
create policy "Qualquer um pode ver trajetoria"
  on public.trajetoria for select
  to anon, authenticated using (true);

drop policy if exists "Admin pode inserir trajetoria" on public.trajetoria;
create policy "Admin pode inserir trajetoria"
  on public.trajetoria for insert
  to authenticated with check (true);

drop policy if exists "Admin pode atualizar trajetoria" on public.trajetoria;
create policy "Admin pode atualizar trajetoria"
  on public.trajetoria for update
  to authenticated using (true) with check (true);

drop policy if exists "Admin pode apagar trajetoria" on public.trajetoria;
create policy "Admin pode apagar trajetoria"
  on public.trajetoria for delete
  to authenticated using (true);

-- Valor inicial: mesmos 6 marcos que já estavam fixos no código, pra não mudar nada
-- visualmente até o admin editar pelo painel. imagem_url fica null (o site usa o selo
-- padrão como fallback enquanto não houver upload de foto pelo admin).
insert into public.trajetoria (ano, categoria, titulo, descricao)
select * from (values
  ('2020 - 2021', 'IDEALIZAÇÃO', 'O Início de um Sonho', 'A Estude Seguro nasceu para ampliar o acesso à educação técnica de qualidade, tornando as matrículas em cursos EAD mais acessíveis, seguras e eficientes, contribuindo para o desenvolvimento pessoal e profissional.'),
  ('2022', 'EAD', 'Metodologia EAD', 'Com uma metodologia EAD desenvolvida para oferecer flexibilidade, autonomia e praticidade, permitindo que você estude de onde estiver e no horário que melhor se adapte à sua rotina. Unindo tecnologia, eficiência e segurança para facilitar sua formação.'),
  ('2023', 'EXPANSÃO', 'Crescimento Exponencial', 'Oferecemos um amplo portfólio de cursos técnicos alinhados às demandas do mercado, permitindo que cada aluno escolha a formação ideal para alcançar seus objetivos com qualidade e confiança.'),
  ('2024', 'INOVAÇÃO', 'Crescimento e Impacto', 'O crescimento da Estude Seguro é baseado em segurança, transparência e credibilidade. Garantimos que cada matrícula seja realizada com respaldo legal, proporcionando confiança desde a inscrição até a conquista do diploma.'),
  ('2025 - 2026', 'CONSOLIDAÇÃO', 'Suporte e Acompanhamento', 'Oferecemos atendimento humanizado e acompanhamento durante toda a jornada acadêmica. Nossos consultores educacionais estão prontos para orientar cada etapa com clareza, segurança e conformidade com a legislação.'),
  ('2026', 'O FUTURO CONTINUA', 'O Futuro Continua', 'Investimos continuamente em inovação, tecnologia e soluções educacionais para oferecer uma experiência de ensino moderna, acessível e eficiente, preparando nossos alunos para os desafios do futuro.')
) as seed(ano, categoria, titulo, descricao)
where not exists (select 1 from public.trajetoria);
