// ============================================================================
// Estoque da campanha "Resgate seu Prêmio" — testes em PostgreSQL de verdade
// ----------------------------------------------------------------------------
// Roda supabase-resgate-estoque.sql dentro de uma instância PGlite
// (PostgreSQL 18 compilado para WASM). Não é mock: é o mesmo plpgsql, o mesmo
// planejador, o mesmo advisory lock.
//
// O QUE ESTE TESTE PROVA:      a migration produz os 7 prêmios com o estoque e
//                              os pesos combinados; o sorteio respeita
//                              peso × quantidade_disponivel; o estoque baixa uma
//                              unidade por giro e nunca fica negativo; prêmio
//                              esgotado ou com peso 0 nunca é sorteado; o
//                              fallback devolve "Não foi dessa vez" sem inflar
//                              estoque; voucher não se reutiliza.
//
// O QUE ESTE TESTE NÃO PROVA:  concorrência real. PGlite tem uma conexão só,
//                              então não existem duas transações simultâneas
//                              aqui. O que dá para verificar — e está no teste
//                              4 — é que a trava de estoque impede o segundo
//                              vencedor e que o advisory lock está no caminho.
//
// Como rodar (a dependência fica fora do projeto, package.json não é tocado):
//   npm i @electric-sql/pglite --prefix <pasta-temporaria>
//   NODE_PATH=<pasta-temporaria>/node_modules node testes/resgate-estoque.mjs
// ============================================================================

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const { PGlite } = await import('@electric-sql/pglite');

const raiz = join(dirname(fileURLToPath(import.meta.url)), '..');
const db = new PGlite();

let passou = 0;
let falhou = 0;

function ok(nome, condicao, detalhe = '') {
  if (condicao) {
    passou += 1;
    console.log(`  ✓ ${nome}`);
  } else {
    falhou += 1;
    console.log(`  ✗ ${nome}${detalhe ? ` — ${detalhe}` : ''}`);
  }
}

const linhas = async (sql, params) => (await db.query(sql, params)).rows;
const uma = async (sql, params) => (await linhas(sql, params))[0];

// --- Estado do banco antes da migration -------------------------------------
// Reproduz o schema criado por supabase-resgate-premio-setup.sql e os prêmios
// de teste que hoje estão em produção, para provar que a migration os tira da
// roleta sem apagá-los.
async function prepararBase() {
  await db.exec(`
    -- Papéis que o Supabase já traz prontos e que os GRANTs da migration citam.
    create role anon;
    create role authenticated;

    create table public.resgate_funcionarios (
      id bigint generated by default as identity primary key,
      nome text not null,
      ativo boolean not null default true,
      created_at timestamptz not null default now()
    );

    create table public.resgate_premios (
      id bigint generated by default as identity primary key,
      nome text not null,
      rotulo text,
      rotulo_secundario text,
      peso integer not null default 1 check (peso >= 0),
      ativo boolean not null default true,
      ordem integer not null default 0,
      created_at timestamptz not null default now()
    );

    create table public.resgate_vouchers (
      id bigint generated by default as identity primary key,
      codigo text not null unique,
      usado boolean not null default false,
      created_at timestamptz not null default now(),
      usado_em timestamptz,
      participante_nome text,
      funcionario_id bigint references public.resgate_funcionarios (id) on delete set null,
      funcionario_nome text,
      premio_id bigint references public.resgate_premios (id) on delete set null,
      premio_nome text
    );

    -- Stubs das dependências da série de segurança. O rate limit é controlado
    -- por uma tabelinha para o teste conseguir simular o limite estourado.
    create table public.teste_config (chave text primary key, valor boolean not null);
    insert into public.teste_config values ('rate_limit_ok', true), ('eh_admin', true);

    create or replace function public.consumir_rate_limit(p_acao text, p_limite integer, p_janela interval)
    returns boolean language sql as $fn$
      select valor from public.teste_config where chave = 'rate_limit_ok';
    $fn$;

    create or replace function public.eh_admin()
    returns boolean language sql as $fn$
      select valor from public.teste_config where chave = 'eh_admin';
    $fn$;

    insert into public.resgate_funcionarios (nome) values ('Responsável'), ('reponsavel2');

    insert into public.resgate_premios (nome, rotulo, rotulo_secundario, peso, ordem) values
      ('10% de desconto', '10%', 'DE DESCONTO', 1, 0),
      ('Mentoria', null, 'MENTORIA', 1, 1),
      ('20% de desconto', '20%', 'DE DESCONTO', 1, 2),
      ('TESTE', 'TT', 'TESTE', 1, 3),
      ('TESTE2', '2', 'TESTE', 1, 4),
      ('TESTE3', '3', 'TESTE', 1, 5);
  `);
}

// --- Utilitários do giro ----------------------------------------------------
let contadorVoucher = 0;

async function novoVoucher() {
  contadorVoucher += 1;
  const codigo = `TST${String(contadorVoucher).padStart(7, '0')}`;
  await db.query('insert into public.resgate_vouchers (codigo) values ($1)', [codigo]);
  return codigo;
}

async function girar(codigo, nome = 'Fulano de Tal', funcionarioId = 1) {
  return uma('select * from public.girar_roleta_resgate($1, $2, $3)', [nome, codigo, funcionarioId]);
}

async function girarNovo() {
  return girar(await novoVoucher());
}

const estoqueDe = async (nome) =>
  Number((await uma('select quantidade_disponivel from public.resgate_premios where nome = $1', [nome]))
    .quantidade_disponivel);

const zerarPesosExceto = async (nome) => {
  await db.query('update public.resgate_premios set peso = 0');
  await db.query('update public.resgate_premios set peso = 1 where nome = $1', [nome]);
};

const restaurarPesos = async () => {
  await db.exec(`
    update public.resgate_premios set peso = case nome
      when 'Pós-graduação / Superior Sequencial' then 1.5
      when 'Profissionalizantes' then 1.0
      when 'Não foi dessa vez' then 0.7
      when 'R$ 20' then 1.0
      when 'R$ 50' then 0.8
      when 'R$ 10' then 0.8
      when 'R$ 100' then 0.5
      else 0 end;
  `);
};

// ============================================================================
console.log('\n=== MIGRATION ===');
await prepararBase();
try {
  await db.exec(readFileSync(join(raiz, 'supabase-resgate-estoque.sql'), 'utf8'));
  ok('supabase-resgate-estoque.sql aplicou sem erro', true);
} catch (erro) {
  console.log(`  ✗ a migration falhou: ${erro.message}`);
  process.exit(1);
}

{
  const esperado = {
    'Pós-graduação / Superior Sequencial': [15, 1.5],
    Profissionalizantes: [150, 1.0],
    'Não foi dessa vez': [40, 0.7],
    'R$ 20': [15, 1.0],
    'R$ 50': [6, 0.8],
    'R$ 10': [100, 0.8],
    'R$ 100': [4, 0.5],
  };

  const campanha = await linhas(
    'select nome, peso::float8 as peso, quantidade_total, quantidade_disponivel, eh_consolacao, ordem from public.resgate_premios where ativo order by ordem',
  );

  ok('os 7 prêmios da campanha estão ativos', campanha.length === 7, `veio ${campanha.length}`);

  let estoquesCorretos = true;
  let pesosCorretos = true;
  for (const linha of campanha) {
    const alvo = esperado[linha.nome];
    if (!alvo) {
      estoquesCorretos = false;
      continue;
    }
    if (Number(linha.quantidade_total) !== alvo[0] || Number(linha.quantidade_disponivel) !== alvo[0]) {
      estoquesCorretos = false;
    }
    if (Number(linha.peso) !== alvo[1]) pesosCorretos = false;
  }
  ok('estoque de cada prêmio bate com a tabela combinada', estoquesCorretos);
  ok('pesos iniciais batem com a tabela combinada', pesosCorretos);

  const total = campanha.reduce((s, l) => s + Number(l.quantidade_total), 0);
  ok('estoque total é 330', total === 330, `veio ${total}`);

  const consolacao = campanha.filter((l) => l.eh_consolacao);
  ok(
    'só "Não foi dessa vez" está marcado como consolação',
    consolacao.length === 1 && consolacao[0].nome === 'Não foi dessa vez',
  );

  const antigos = await linhas("select nome, ativo, peso::float8 as peso from public.resgate_premios where nome like 'TESTE%' or nome = 'Mentoria'");
  ok('prêmios de teste continuam existindo (ids preservados)', antigos.length === 4, `veio ${antigos.length}`);
  ok('prêmios de teste saíram da roleta', antigos.every((l) => l.ativo === false && Number(l.peso) === 0));

  const decimal = await uma("select peso::text as peso from public.resgate_premios where nome = 'Pós-graduação / Superior Sequencial'");
  ok('peso aceita casas decimais', Number(decimal.peso) === 1.5, `veio ${decimal.peso}`);
}

// ============================================================================
console.log('\n=== CONSTRAINTS ===');
{
  const recusa = async (sql) => {
    try {
      await db.query(sql);
      return false;
    } catch {
      return true;
    }
  };

  ok('peso negativo é recusado', await recusa("update public.resgate_premios set peso = -1 where nome = 'R$ 10'"));
  ok(
    'quantidade_disponivel negativa é recusada',
    await recusa("update public.resgate_premios set quantidade_disponivel = -1 where nome = 'R$ 10'"),
  );
  ok(
    'quantidade_disponivel acima do total é recusada',
    await recusa("update public.resgate_premios set quantidade_disponivel = 999 where nome = 'R$ 10'"),
  );

  // Vale também pela RPC de pesos, que é por onde o painel escreve.
  let rpcRecusou = false;
  try {
    await db.query(`select public.salvar_pesos_resgate('[{"id": 1, "peso": -1}]'::jsonb)`);
  } catch {
    rpcRecusou = true;
  }
  ok('salvar_pesos_resgate recusa peso negativo', rpcRecusou);

  await db.query("update public.teste_config set valor = false where chave = 'eh_admin'");
  let bloqueouNaoAdmin = false;
  try {
    await db.query(`select public.salvar_pesos_resgate('[{"id": 1, "peso": 1}]'::jsonb)`);
  } catch {
    bloqueouNaoAdmin = true;
  }
  ok('salvar_pesos_resgate exige admin', bloqueouNaoAdmin);
  await db.query("update public.teste_config set valor = true where chave = 'eh_admin'");
}

// ============================================================================
console.log('\n=== TESTE 1 — prêmio normal baixa 1 unidade ===');
{
  await zerarPesosExceto('R$ 10');
  const antes = await estoqueDe('R$ 10');
  const r = await girarNovo();
  const depois = await estoqueDe('R$ 10');
  ok('giro retornou sucesso', r.resultado === 'sucesso', r.resultado);
  ok('prêmio retornado é R$ 10', r.premio_nome === 'R$ 10', r.premio_nome);
  ok(`estoque foi de ${antes} para ${antes - 1}`, depois === antes - 1, `veio ${depois}`);
}

// ============================================================================
console.log('\n=== TESTE 2 — prêmio com 1 unidade ===');
{
  await db.query("update public.resgate_premios set quantidade_disponivel = 1 where nome = 'R$ 100'");
  await zerarPesosExceto('R$ 100');
  const r = await girarNovo();
  const depois = await estoqueDe('R$ 100');
  ok('a única unidade foi entregue', r.resultado === 'sucesso' && r.premio_nome === 'R$ 100');
  ok('estoque foi de 1 para 0', depois === 0, `veio ${depois}`);
  const visivel = await uma("select ativo from public.resgate_premios where nome = 'R$ 100'");
  ok('prêmio esgotado continua ativo (segue na roleta)', visivel.ativo === true);
}

// ============================================================================
console.log('\n=== TESTE 3 — prêmio esgotado nunca sai ===');
{
  // R$ 100 está em 0 desde o teste 2. Peso alto de propósito: se o estoque não
  // fosse respeitado, ele dominaria o sorteio.
  await restaurarPesos();
  await db.query("update public.resgate_premios set peso = 99 where nome = 'R$ 100'");

  let saiuEsgotado = false;
  for (let i = 0; i < 60; i++) {
    const r = await girarNovo();
    if (r.premio_nome === 'R$ 100') saiuEsgotado = true;
  }
  ok('R$ 100 esgotado não saiu em 60 giros, mesmo com peso 99', !saiuEsgotado);
  ok('estoque de R$ 100 continua 0 (nunca negativo)', (await estoqueDe('R$ 100')) === 0);
  await restaurarPesos();
}

// ============================================================================
console.log('\n=== TESTE 4 — trava de concorrência ===');
{
  // PGlite tem uma conexão só: não dá para abrir duas transações simultâneas.
  // O que dá para provar aqui é que (a) o advisory lock está no caminho do
  // giro e (b) a segunda trava — `quantidade_disponivel > 0` no UPDATE —
  // impede um segundo vencedor mesmo se o lock falhasse.
  const fonte = readFileSync(join(raiz, 'supabase-resgate-estoque.sql'), 'utf8');
  ok('o giro toma advisory lock antes de ler o estoque', fonte.includes('pg_advisory_xact_lock'));
  ok(
    'o UPDATE de baixa exige quantidade_disponivel > 0',
    /update public\.resgate_premios[\s\S]*?quantidade_disponivel = quantidade_disponivel - 1[\s\S]*?where id = v_premio_id and quantidade_disponivel > 0/.test(fonte),
  );

  await db.query("update public.resgate_premios set quantidade_disponivel = 1 where nome = 'R$ 50'");
  await zerarPesosExceto('R$ 50');

  const primeiro = await girarNovo();
  const segundo = await girarNovo();
  ok('primeiro giro leva a única unidade', primeiro.premio_nome === 'R$ 50');
  ok('segundo giro NÃO leva o mesmo prêmio', segundo.premio_nome !== 'R$ 50', segundo.premio_nome);
  ok('estoque parou em 0, não em -1', (await estoqueDe('R$ 50')) === 0);

  // A trava do UPDATE isolada: força a corrida que o lock normalmente impede.
  await db.query("update public.resgate_premios set quantidade_disponivel = 0 where nome = 'R$ 50'");
  const forcado = await db.query(
    "update public.resgate_premios set quantidade_disponivel = quantidade_disponivel - 1 where nome = 'R$ 50' and quantidade_disponivel > 0",
  );
  ok('baixa em estoque zerado não afeta nenhuma linha', forcado.affectedRows === 0, `afetou ${forcado.affectedRows}`);
  await restaurarPesos();
}

// ============================================================================
console.log('\n=== TESTE 5 — peso zero ===');
{
  await restaurarPesos();
  await db.query("update public.resgate_premios set peso = 0 where nome = 'Profissionalizantes'");
  const antes = await estoqueDe('Profissionalizantes');

  let saiu = false;
  for (let i = 0; i < 60; i++) {
    const r = await girarNovo();
    if (r.premio_nome === 'Profissionalizantes') saiu = true;
  }
  ok('prêmio com peso 0 não foi sorteado em 60 giros', !saiu);
  ok('estoque dele não foi tocado', (await estoqueDe('Profissionalizantes')) === antes);
  const visivel = await uma("select ativo from public.resgate_premios where nome = 'Profissionalizantes'");
  ok('continua ativo (segue na roleta)', visivel.ativo === true);
  await restaurarPesos();
}

// ============================================================================
console.log('\n=== TESTE 6 — fallback "Não foi dessa vez" ===');
{
  await db.exec(`
    update public.resgate_premios
    set quantidade_disponivel = 0
    where ativo and not eh_consolacao;
  `);

  // (a) consolação ainda com estoque: sai pelo sorteio normal e baixa 1.
  await db.query("update public.resgate_premios set quantidade_disponivel = 5 where eh_consolacao");
  const a = await girarNovo();
  ok('com todos os limitados zerados, o resultado é "Não foi dessa vez"', a.premio_nome === 'Não foi dessa vez', a.premio_nome);
  ok('estoque da consolação baixou de 5 para 4', (await estoqueDe('Não foi dessa vez')) === 4);

  // (b) consolação também zerada: continua respondendo, sem estoque negativo.
  await db.query("update public.resgate_premios set quantidade_disponivel = 0 where eh_consolacao");
  const b = await girarNovo();
  ok('consolação zerada ainda responde "Não foi dessa vez"', b.premio_nome === 'Não foi dessa vez', b.premio_nome);
  ok('resultado continua sendo sucesso', b.resultado === 'sucesso', b.resultado);
  ok('estoque da consolação segue 0, nunca negativo', (await estoqueDe('Não foi dessa vez')) === 0);
  ok(
    'quantidade_total da consolação continua 40 (não foi inflada)',
    Number((await uma("select quantidade_total from public.resgate_premios where eh_consolacao")).quantidade_total) === 40,
  );
}

// ============================================================================
console.log('\n=== TESTE 7 — 400 giros para 330 prêmios ===');
{
  // Banco limpo, campanha do zero.
  await db.exec('delete from public.resgate_vouchers');
  await db.exec(`
    update public.resgate_premios
    set quantidade_disponivel = quantidade_total
    where ativo;
  `);
  await restaurarPesos();

  const contagem = new Map();
  let erros = 0;
  for (let i = 0; i < 400; i++) {
    const r = await girarNovo();
    if (r.resultado !== 'sucesso') erros += 1;
    contagem.set(r.premio_nome, (contagem.get(r.premio_nome) || 0) + 1);
  }

  ok('os 400 giros terminaram sem erro', erros === 0, `${erros} com erro`);

  const finais = await linhas(
    'select nome, quantidade_total, quantidade_disponivel from public.resgate_premios where ativo order by ordem',
  );
  ok('nenhum estoque ficou negativo', finais.every((l) => Number(l.quantidade_disponivel) >= 0));

  const entregues = finais.reduce(
    (s, l) => s + (Number(l.quantidade_total) - Number(l.quantidade_disponivel)),
    0,
  );
  ok('exatamente 330 unidades foram consumidas', entregues === 330, `foram ${entregues}`);

  const consolacao = contagem.get('Não foi dessa vez') || 0;
  ok('os 70 giros excedentes viraram "Não foi dessa vez"', consolacao >= 70, `consolação saiu ${consolacao}x`);

  const usados = Number((await uma('select count(*)::int as n from public.resgate_vouchers where usado')).n);
  ok('os 400 vouchers foram queimados', usados === 400, `foram ${usados}`);

  console.log('\n  distribuição dos 400 giros:');
  for (const l of finais) {
    const saiu = contagem.get(l.nome) || 0;
    console.log(
      `    ${l.nome.padEnd(36)} saiu ${String(saiu).padStart(3)}x   estoque ${l.quantidade_disponivel}/${l.quantidade_total}`,
    );
  }
}

// ============================================================================
console.log('\n=== TESTE 8 — voucher e proteções preservadas ===');
{
  await db.exec("update public.resgate_premios set quantidade_disponivel = quantidade_total where ativo");
  await restaurarPesos();

  const codigo = await novoVoucher();
  const primeiro = await girar(codigo);
  ok('primeiro uso do voucher funciona', primeiro.resultado === 'sucesso');

  const segundo = await girar(codigo);
  ok('reuso do voucher é recusado', segundo.resultado === 'voucher_invalido', segundo.resultado);

  const inexistente = await girar('NAOEXISTE9');
  ok(
    'código inexistente devolve a MESMA resposta do já usado (sem oráculo)',
    inexistente.resultado === 'voucher_invalido',
  );

  const semNome = await girar(await novoVoucher(), 'Jo');
  ok('nome curto é recusado', semNome.resultado === 'voucher_invalido');

  const funcInvalido = await girar(await novoVoucher(), 'Fulano de Tal', 9999);
  ok('funcionário inexistente é recusado', funcInvalido.resultado === 'funcionario_invalido');

  await db.query("update public.resgate_funcionarios set ativo = false where id = 2");
  const funcInativo = await girar(await novoVoucher(), 'Fulano de Tal', 2);
  ok('funcionário inativo é recusado', funcInativo.resultado === 'funcionario_invalido');
  await db.query("update public.resgate_funcionarios set ativo = true where id = 2");

  await db.query("update public.teste_config set valor = false where chave = 'rate_limit_ok'");
  const limitado = await girar(await novoVoucher());
  ok('rate limit continua barrando', limitado.resultado === 'limite_excedido', limitado.resultado);
  await db.query("update public.teste_config set valor = true where chave = 'rate_limit_ok'");

  const naoQueimou = Number(
    (await uma('select count(*)::int as n from public.resgate_vouchers where not usado')).n,
  );
  ok('vouchers recusados não foram queimados', naoQueimou >= 4, `restaram ${naoQueimou}`);
}

// ============================================================================
console.log('\n=== HISTÓRICO E RANKING ===');
{
  const giro = await uma(`
    select participante_nome, funcionario_id, funcionario_nome, premio_id, premio_nome, usado_em, codigo
    from public.resgate_vouchers
    where usado
    order by usado_em desc
    limit 1
  `);
  ok('histórico grava participante', !!giro.participante_nome);
  ok('histórico grava funcionário (id e nome)', !!giro.funcionario_id && !!giro.funcionario_nome);
  ok('histórico grava prêmio (id e nome)', !!giro.premio_id && !!giro.premio_nome);
  ok('histórico grava data/hora e voucher', !!giro.usado_em && !!giro.codigo);

  const ranking = await linhas(`
    select f.nome, count(v.id)::int as giros
    from public.resgate_funcionarios f
    left join public.resgate_vouchers v on v.funcionario_id = f.id and v.usado
    group by f.id, f.nome
    order by giros desc
  `);
  ok('ranking conta só giros efetivados', ranking[0].giros > 0);
  const totalRanking = ranking.reduce((s, l) => s + l.giros, 0);
  const totalUsados = Number((await uma('select count(*)::int as n from public.resgate_vouchers where usado')).n);
  ok('soma do ranking bate com os vouchers usados', totalRanking === totalUsados, `${totalRanking} vs ${totalUsados}`);
}

// ============================================================================
console.log(`\n=== RESULTADO: ${passou} passaram, ${falhou} falharam ===\n`);
await db.close();
process.exit(falhou === 0 ? 0 : 1);
