export const tecToGrad = {
  "Técnico em Administração": ["Gestão Comercial", "Marketing", "Marketing Digital", "Processos Gerenciais", "Gestão de Recursos Humanos", "Gestão de Cooperativas", "Gestão da Qualidade", "Gestão Financeira", "Gestão Pública", "Logística", "Secretariado", "Serviços Jurídicos", "Serviços Jurídicos e Notariais"],
  "Técnico em Agente Comunitário de Saúde": ["Gestão Hospitalar"],
  "Técnico em Agricultura": ["Gestão Ambiental", "Gestão do Agronegócio", "Gestão da Produção Industrial"],
  "Técnico em Agrimensura": ["Designe de Interiores"],
  "Técnico em Agronegócios": ["Gestão do Agronegócio", "Gestão de Cooperativas"],
  "Técnico em Agropecuária": ["Gestão do Agronegócio", "Gestão Ambiental"],
  "Técnico em Análises Clínicas": ["Gestão Hospitalar", "Gestão da Qualidade"],
  "Técnico em Automação Industrial": ["Gestão da Produção Industrial", "Gestão da Qualidade"],
  "Técnico em Computação Gráfica": ["Design Gráfico"],
  "Técnico em Contabilidade": ["Gestão Financeira", "Gestão Comercial", "Processos Gerenciais", "Gestão de Cooperativas", "Gestão Pública", "Secretariado"],
  "Técnico em Desenvolvimento de Sistemas": ["Análise e Desenvolvimento de Sistemas", "Sistemas para Internet", "Gestão da Tecnologia da Informação", "Segurança da Informação", "Jogos Digitais"],
  "Técnico em Design Gráfico": ["Design Gráfico"],
  "Técnico em Edificações": ["Gestão da Produção Industrial", "Gestão da Qualidade", "Gestão Ambiental", "Gestão da Tecnologia da Informação", "Processos Gerenciais", "Gestão Comercial", "Gestão Financeira", "Gestão de Cooperativas", "Gestão Pública", "Logística", "Secretariado", "Segurança no Trabalho"],
  "Técnico em Eletroeletrônica": ["Gestão da Produção Industrial", "Gestão da Qualidade", "Gestão da Tecnologia da Informação", "Análise e Desenvolvimento de Sistemas", "Segurança da Informação", "Segurança no Trabalho", "Gestão Ambiental"],
  "Técnico em Eletromecânica": ["Gestão da Produção Industrial", "Gestão da Qualidade"],
  "Técnico em Eletrônica": ["Análise e Desenvolvimento de Sistemas", "Gestão da Tecnologia da Informação", "Gestão da Produção Industrial", "Gestão da Qualidade", "Segurança da Informação", "Segurança no Trabalho"],
  "Técnico em Eletrotécnica": ["Gestão da Produção Industrial"],
  "Técnico em Energia Renovável": ["Gestão Ambiental", "Gestão da Qualidade"],
  "Técnico em Farmácia": ["Gestão Hospitalar"],
  "Técnico em Finanças": ["Gestão Financeira", "Gestão Comercial", "Processos Gerenciais", "Gestão de Cooperativas", "Gestão Pública"],
  "Técnico em Informática": ["Análise e Desenvolvimento de Sistemas", "Sistemas para Internet", "Gestão da Tecnologia da Informação", "Segurança da Informação", "Big Data e Inteligência Analítica", "Jogos Digitais", "Design Gráfico", "Gestão da Qualidade"],
  "Técnico em Informática para Internet": ["Sistemas para Internet", "Análise e Desenvolvimento de Sistemas", "Gestão da Tecnologia da Informação"],
  "Técnico em Logística": ["Logística", "Gestão Comercial", "Processos Gerenciais"],
  "Técnico em Manutenção Automotiva": ["Gestão da Produção Industrial", "Gestão da Qualidade"],
  "Técnico em Manutenção de Máquinas Industriais": ["Gestão da Produção Industrial", "Gestão da Qualidade"],
  "Técnico em Marketing": ["Marketing", "Marketing Digital", "Gestão Comercial", "Processos Gerenciais"],
  "Técnico em Mecânica": ["Gestão da Produção Industrial", "Gestão da Qualidade", "Gestão Ambiental"],
  "Técnico em Mecatrônica": ["Análise e Desenvolvimento de Sistemas", "Gestão da Tecnologia da Informação", "Gestão da Produção Industrial", "Gestão da Qualidade", "Segurança da Informação"],
  "Técnico em Meio Ambiente": ["Gestão Ambiental"],
  "Técnico em Mineração": ["Gestão Ambiental"],
  "Técnico em Publicidade": ["Marketing"],
  "Técnico em Qualidade": ["Gestão da Qualidade", "Gestão da Produção Industrial", "Processos Gerenciais", "Gestão Comercial", "Gestão Ambiental"],
  "Técnico em Química": ["Gestão Ambiental"],
  "Técnico em Recursos Humanos": ["Gestão de Recursos Humanos", "Processos Gerenciais", "Gestão Comercial", "Secretariado"],
  "Técnico em Redes de Computadores": ["Análise e Desenvolvimento de Sistemas", "Gestão da Tecnologia da Informação", "Segurança da Informação", "Big Data e Inteligência Analítica"],
  "Técnico em Refrigeração e Climatização": ["Gestão da Produção Industrial", "Gestão da Qualidade"],
  "Técnico em Secretaria Escolar": ["Tutoria para Educação a Distância"],
  "Técnico em Segurança do Trabalho": ["Segurança no Trabalho", "Gestão da Qualidade", "Gestão da Produção Industrial"],
  "Técnico em Serviços Jurídicos": ["Serviços Jurídicos", "Serviços Jurídicos e Notariais", "Gestão Pública"],
  "Técnico em Sistemas de Energia Renovável": ["Gestão Ambiental", "Gestão da Qualidade"],
  "Técnico em Telecomunicações": ["Análise e Desenvolvimento de Sistemas", "Gestão da Tecnologia da Informação", "Segurança da Informação", "Big Data e Inteligência Analítica"],
  "Técnico em Transações Imobiliárias": ["Negócios Imobiliários", "Gestão Comercial"],
  "Técnico em Vendas": ["Gestão Comercial", "Marketing", "Marketing Digital", "Processos Gerenciais", "Gestão de Cooperativas", "Negócios Imobiliários"],
};

export const gradToTec = {
  "Análise e Desenvolvimento de Sistemas": ["Técnico em Desenvolvimento de Sistemas", "Técnico em Eletroeletrônica", "Técnico em Eletrônica", "Técnico em Informática", "Técnico em Informática para Internet", "Técnico em Mecatrônica", "Técnico em Redes de Computadores", "Técnico em Telecomunicações"],
  "Big Data e Inteligência Analítica": ["Técnico em Informática", "Técnico em Redes de Computadores", "Técnico em Telecomunicações", "Técnico em Desenvolvimento de Sistemas"],
  "Design Gráfico": ["Técnico em Computação Gráfica", "Técnico em Design Gráfico", "Técnico em Informática", "Técnico em Desenvolvimento de Sistemas", "Técnico em Informática para Internet", "Técnico em Mecatrônica"],
  "Designe de Interiores": ["Técnico em Agrimensura"],
  "Gestão Ambiental": ["Técnico em Agricultura", "Técnico em Agropecuária", "Técnico em Eletroeletrônica", "Técnico em Energia Renovável", "Técnico em Mecânica", "Técnico em Meio Ambiente", "Técnico em Mineração", "Técnico em Qualidade", "Técnico em Química", "Técnico em Sistemas de Energia Renovável", "Técnico em Edificações"],
  "Gestão Comercial": ["Técnico em Administração", "Técnico em Contabilidade", "Técnico em Edificações", "Técnico em Finanças", "Técnico em Logística", "Técnico em Marketing", "Técnico em Qualidade", "Técnico em Recursos Humanos", "Técnico em Transações Imobiliárias", "Técnico em Vendas"],
  "Gestão da Produção Industrial": ["Técnico em Agricultura", "Técnico em Automação Industrial", "Técnico em Edificações", "Técnico em Eletroeletrônica", "Técnico em Eletromecânica", "Técnico em Eletrônica", "Técnico em Eletrotécnica", "Técnico em Manutenção Automotiva", "Técnico em Manutenção de Máquinas Industriais", "Técnico em Mecânica", "Técnico em Mecatrônica", "Técnico em Qualidade", "Técnico em Refrigeração e Climatização", "Técnico em Segurança do Trabalho"],
  "Gestão da Qualidade": ["Técnico em Análises Clínicas", "Técnico em Automação Industrial", "Técnico em Edificações", "Técnico em Eletroeletrônica", "Técnico em Eletromecânica", "Técnico em Eletrônica", "Técnico em Energia Renovável", "Técnico em Informática", "Técnico em Manutenção Automotiva", "Técnico em Manutenção de Máquinas Industriais", "Técnico em Mecânica", "Técnico em Mecatrônica", "Técnico em Qualidade", "Técnico em Refrigeração e Climatização", "Técnico em Segurança do Trabalho", "Técnico em Sistemas de Energia Renovável"],
  "Gestão da Tecnologia da Informação": ["Técnico em Desenvolvimento de Sistemas", "Técnico em Edificações", "Técnico em Eletroeletrônica", "Técnico em Eletrônica", "Técnico em Informática", "Técnico em Informática para Internet", "Técnico em Mecatrônica", "Técnico em Telecomunicações"],
  "Gestão de Cooperativas": ["Técnico em Administração", "Técnico em Agronegócios", "Técnico em Contabilidade", "Técnico em Edificações", "Técnico em Finanças", "Técnico em Vendas"],
  "Gestão de Recursos Humanos": ["Técnico em Administração", "Técnico em Recursos Humanos", "Técnico em Contabilidade", "Técnico em Finanças"],
  "Gestão de Segurança Privada": ["Técnico em Segurança do Trabalho", "Técnico em Eletroeletrônica"],
  "Gestão do Agronegócio": ["Técnico em Agricultura", "Técnico em Agronegócios", "Técnico em Agropecuária"],
  "Gestão Financeira": ["Técnico em Administração", "Técnico em Contabilidade", "Técnico em Edificações", "Técnico em Finanças", "Técnico em Logística", "Técnico em Vendas"],
  "Gestão Hospitalar": ["Técnico em Agente Comunitário de Saúde", "Técnico em Análises Clínicas", "Técnico em Farmácia"],
  "Gestão Pública": ["Técnico em Administração", "Técnico em Contabilidade", "Técnico em Edificações", "Técnico em Finanças", "Técnico em Serviços Jurídicos"],
  "Jogos Digitais": ["Técnico em Desenvolvimento de Sistemas", "Técnico em Informática", "Técnico em Mecatrônica"],
  "Logística": ["Técnico em Edificações", "Técnico em Logística"],
  "Marketing": ["Técnico em Administração", "Técnico em Marketing", "Técnico em Publicidade", "Técnico em Vendas"],
  "Marketing Digital": ["Técnico em Administração", "Técnico em Marketing", "Técnico em Vendas"],
  "Negócios Imobiliários": ["Técnico em Transações Imobiliárias", "Técnico em Vendas", "Técnico em Administração"],
  "Processos Gerenciais": ["Técnico em Administração", "Técnico em Contabilidade", "Técnico em Edificações", "Técnico em Finanças", "Técnico em Logística", "Técnico em Marketing", "Técnico em Qualidade", "Técnico em Recursos Humanos", "Técnico em Vendas", "Técnico em Manutenção Automotiva"],
  "Secretariado": ["Técnico em Administração", "Técnico em Contabilidade", "Técnico em Edificações", "Técnico em Recursos Humanos", "Técnico em Secretaria Escolar"],
  "Segurança da Informação": ["Técnico em Desenvolvimento de Sistemas", "Técnico em Eletroeletrônica", "Técnico em Eletrônica", "Técnico em Informática", "Técnico em Mecatrônica", "Técnico em Redes de Computadores", "Técnico em Telecomunicações"],
  "Segurança no Trabalho": ["Técnico em Edificações", "Técnico em Eletroeletrônica", "Técnico em Eletrônica", "Técnico em Segurança do Trabalho"],
  "Serviços Jurídicos": ["Técnico em Administração", "Técnico em Serviços Jurídicos", "Técnico em Contabilidade", "Técnico em Finanças"],
  "Serviços Jurídicos e Notariais": ["Técnico em Administração", "Técnico em Serviços Jurídicos", "Técnico em Contabilidade", "Técnico em Finanças"],
  "Sistemas para Internet": ["Técnico em Desenvolvimento de Sistemas", "Técnico em Informática", "Técnico em Informática para Internet", "Técnico em Mecatrônica"],
  "Tutoria para Educação a Distância": ["Técnico em Secretaria Escolar"],
};
